sudo: false

language: python

python:
  - "3.6"

env:
  - TRAVIS=true

before_install:
  - sudo add-apt-repository ppa:nilarimogard/webupd8
  - sudo apt-get update
  - sudo apt-get install http://packages.ubuntu.com/trusty/python-wxgtk2.8

install:
  - pip install -r requirements.txt

script:
  - pytest && exit 0
