sudo: false

language: python

python:
  - "3.6"

env:
  - TRAVIS=true

before_install:
  - sudo apt-get install python-wxgtk2.8

install:
  - pip install -r requirements.txt

script:
  - pytest && exit 0
